# syntax=docker/dockerfile:1

FROM node:12.18.1

RUN mkdir /app
WORKDIR /app
COPY . /app

#RUN npm install
#RUN npm install -g ts-node typescript '@types/node'
# npx husky install

#RUN npx prisma generate --schema=src/infraestructure/prisma/schema.prisma

# RUN npm run build

ENV PORT 8082

EXPOSE 8082
