version: '3'
services:

  database:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - default
      - gateway
    volumes:
      - ./database_data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "sh"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "8082:8082"
    expose:
      - 8082
    volumes:
        - ./:/app
    links:
      - database
    depends_on:
      - database
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      DATABASE_URL: mongodb://root:example@database:27017/
      DB_NAME: fiuumber
      PORT: 8082
    networks:
      - default
      - gateway
networks:
  default:
    name: localdev
  gateway:
    name: gateway
    external: true

volumes:
  database_data:
    driver: local
